### PR TITLE
Fix memory leak on Windows

### PR DESCRIPTION
**Pull request by codebot**
Unfortunately Windows throws a compiler warning when it sees strdup(); it wants to see _strdup() instead.

### CODE REVIEW

**Comment by tfoote** [comment]
Might it be better to use malloc and strncpy instead to avoid hidden mallocs: http://stackoverflow.com/a/14021507/604099 It's only one more line of code to explicitly malloc and copy.

**Comment by jacquelinekay** [comment]
I haven't mucked around with this part of the codebase very much. @esteve would probably know since he worked a bunch with the TypeSupport to implement C typesupport. (Also, that reminds me--Esteve, you should probably watch the changes we're making to this repo because any changes to files that your pull request moves into a different file will essentially be lost if you don't rebase carefully.)

**Comment by tfoote** [comment]
Yeah, it's just turning it back into a string. Passing the `.c_str()` to it should be adaquate. There are several other instances following that pattern. At least one in parameters and one in QoS.

**Comment by dirk-thomas** [comment]
The same warning is in the sibling file `ServiceTypeSupport.cpp`: http://ci.ros2.org/job/ci_windows/1205/warnings34Result/source.6589365479438003664/#14

**Comment by dirk-thomas** [comment]
Since `ServiceTypeSupport.cpp` has the exact same code with the exact same warnings as this `MessageTypeSupport.cpp` I would say they can be fixed together in this single PR.

**Comment by wjwwood** [comment]
lgtm

**Comment by dirk-thomas** [comment]
Can this be squashed and merged?

**Pull request merged**
