### PR TITLE
Added new functionality: service_is_available

### LINKED ISSUE #14: Implement missing RMW functions
The following functions in src/functions.cpp are not implemented yet:

https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/master/rmw_fastrtps_cpp/src/functions.cpp#L1770-L1806

We haven't exercised these functions outside of the ros1bridge yet, but this limitation came up recently in ros2/system_tests#103.

### PR DESCRIPTION
**Pull request by richiprosima**
This PR contains the service_is_available functionality. To work properly Fast-RTPS has to be in/after commit eProsima/Fast-RTPS@24825bb0de6cc5fdf16949a350c40570f2b00f26. 

Closes #14.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@richiprosima The latest changes in FastRTPS introduced new compiler warnings and test failures. I think you should consider using Travis / AppVeyor to test the codebase automatically. I filled eProsima/Fast-RTPS#62 for this but it applies to all repositories.

**Comment by richiprosima** [comment]
Your nightly CI job started while I was developing this new functionality. It checked out a commit which is not the final commit of my work. Sorry for that, I shouldn't have worked with master branch of Fast-RTPS.
Currently we have an internal Jenkins server for testing Fast-RTPS and other projects. In future we think about Travis. Thanks for your suggestion.

**Comment by wjwwood** [comment]
I'm testing this out right now. I believe we'll need to remove some test exclusions if this starts working:

https://github.com/ros2/examples/issues/113
https://github.com/ros2/system_tests/issues/143

If this works ok, I'll add pr's with the same branch name as this one that remove the test exclusions and/or sleeps so that we can run CI.

**Comment by wjwwood** [comment]
This is looking ok, but what's missing is graph notifications from fastrtps. What this means is that the blocking call `wait_for_service` will always only check the state of the services (with `service_is_available`) once. The intention is that it checks each time the graph changes, but that's not currently happening.

I'm looking into what's missing for that to start working. Based on how far off that functionality is, I'll recommend whether or not to merge this as an incremental improvement or to wait and get the graph change notifications in place first.

**Comment by wjwwood** [comment]
Looks like it is going to be easy to piggy-back the changes to support graph change notifications on top of the changes you made here to support `service_is_available`. I'll update this pr with my changes asap.

**Comment by wjwwood** [comment]
With d7b9634, the "add two ints" client/service examples work really well with each other. I'm going to continue digging into what needs to be done to re-enable all the appropriate tests.

**Comment by wjwwood** [comment]
Starting CI (fastrtps only):

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1726/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1287/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/1661/)

**Comment by wjwwood** [comment]
I'm rerunning CI (still fastrtps only) since I removed an extra sleep that @dhood found:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1727/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1288/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/1662/)

**Comment by wjwwood** [comment]
Actually, all those were invalid because the rclcpp examples were not correctly enabled (I enabled them in a different way locally):

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1729/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1290/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/1663/)

**Comment by wjwwood** [comment]
Ok, the last ones definitely had the new rclcpp examples test for fastrtps:

http://ci.ros2.org/job/ci_linux/1729/testReport/(root)/test_add_two_ints_server_add_two_ints_client__rmw_fastrtps_cpp_/test_executable/

**Comment by wjwwood** [comment]
Ok, I've got passing CI with fastrtps and Connext now that I removed the system_tests pr from this group:

- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1733/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1293/)
- Windows:
  - [Build Status](http://ci.ros2.org/job/ci_windows/1666/)

This pr and the related pr on the examples repository are ready for review and merge.

**Comment by dhood** [comment]
Making it more explicit: `system_tests` using services, when re-enabled for both fastrtps and connext in https://github.com/ros2/system_tests/pull/162, worked fine for fastrtps, just not connext (e.g. http://ci.ros2.org/job/ci_linux/1731/testReport/(root)/test_client_scope_cpp__rmw_fastrtps_cpp_/test_client_scope_cpp/)
so I would say it looks good

**Pull request merged**
