### PR TITLE
Including durability in data reader/writer fastrtps

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Comment by wjwwood** [comment]
Changes look good to me! Thanks for the contribution @ahcorde. I'm going to run our CI job on this branch to make sure it passes the tests:

CI:
- Linux:
  - [Build Status](http://ci.ros2.org/job/ci_linux/1630/)
- OS X:
  - [Build Status](http://ci.ros2.org/job/ci_osx/1226/)

**Comment by gerkey** [comment]
Looks like this change introduced an internal FastRTPS test failure on OSX:

http://ci.ros2.org/job/ci_osx/1226/testReport/projectroot.test.unittest/transport/UDPv6Tests/

@ahcorde, do you know what's going on there?

**Comment by dirk-thomas** [comment]
@gerkey I doubt the test failure is related to this patch since the same test failure is also present in the nightly builds on OS X (http://ci.ros2.org/view/nightly/job/nightly_osx_debug/138/testReport/projectroot.test.unittest/transport/UDPv6Tests/) since Jun 23rd. Btw it is also ticketed: eProsima/Fast-RTPS#55

**Comment by dhood** [comment]
By the way http://ci.ros2.org/job/ci_osx/1228/ is the osx job run again with the same parameters and those connext issues are gone

**Comment by gerkey** [comment]
Well, that's two pieces of great news!

Shall we merge this change, then?

**Comment by dhood** [comment]
if we can leave it for a few hours longer it will help me show that the fix I have underway for https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/issues/48 works independently

**Comment by gerkey** [comment]
Works for me, @dhood.

**Comment by dhood** [comment]
good to merge thanks

**Pull request merged**
